SEED: 100
MODEL:
    ARCH: us_resnet50
    INPUTSHAPE: [224, 224]
    OFA:
        WIDTH_MULT_RANGE: [0.25, 1.0] 
        NUM_SAMPLE_TRAINING: 3
        WIDTH_MULT: 1.0
        SANDWICH: True
        SAMPLE_SCHEDULER: ""
        MOMENTUM_UPDATE: False # False: only update momentum encoder once (max model forward pass)
        DISTILL: True
        DISTILL_CRITERION: CosineSimilarity # distill final representation
        DISTILL_FEATURE: False
        USE_SLIMMABLE: False
        WIDTH_MULT_LIST: [1.0, 0.75, 0.5, 0.25]
        REGULARIZER: False
PRUNE:
    ENABLE_PRUNE: False
    TYPE: structed
    GRANULARITY: channelwise
    STRATEGY: l1norm
    GLOBAL_FACTOR: 1.0
TRAIN:
    EPOCHS: 100
    USE_DDP: True
    USE_AMP: True
    SYNC_BN: False
    DROP_LAST: False # set it to true for DINO
    DATASET: imagenet
    BATCH_SIZE: 60 # per-gpu 
    PRINT_FREQ: 10
    OPTIMIZER: 
        NAME: sgd
        MOMENTUM: 0.9
        WEIGHT_DECAY: 0.0001 # 1e-5
    LR_SCHEDULER:
        WARMUP_EPOCHS: 0
        WARMUP_LR: 0.0002 # 1e-4
        BASE_LR: 0.05 # 1e-2
        MIN_LR: 0.
        TYPE: cosine
    LOSS: 
        CRITERION:
            NAME: CosineSimilarity
        #REGULARIZER:
        #    NAME: PACT
        LAMBDA: 0.0001
    METER:
        NAME: average
        ACC:
            TOPK: [1, 5]
    RUNNER:
        NAME: ssl
SSL:
    TYPE: BYOL
    SETTING:
        DIM: 2048
        HIDDEN_DIM: 2048
        T: 0.5
        MOMENTUM: 0.99
        NEW_DISTILL_HEAD: True

