SEED: 100
MODEL:
    #ARCH: cifar_mobilenetv2
    ARCH: us_cifar_mobilenetv2
    #ARCH: s_cifar_mobilenetv2
    INPUTSHAPE: [32, 32]
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/byol_mobilenetv2_cifar100/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/byol_us_mobilenetv2_cifar100_single_0.25/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/byol_s_mobilenetv2_cifar100_single_1.0/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/seed_us_mobilenetv2_cifar100_0.25_teacher_byol_r50/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/seed_us_mobilenetv2_cifar100_0.25_teacher_byol_r18/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/seed_us_mobilenetv2_cifar100_0.25_teacher_byol_mbv2/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/byol_us_mobilenetv2_cifar100_sandwichOnce_mse_distill_A/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/byol_us_mobilenetv2_cifar100_sandwichOnce_mse_distill_feat_17_distill_mse_A/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/byol_us_mobilenetv2_cifar100_sandwichOnce_mse_distill_A_800ep/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/byol_us_mobilenetv2_cifar100_sandwichOnce_mse_distill_feat_16_distill_mse_A/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/byol_us_mobilenetv2_cifar100_sandwichOnce_mse_distill_feat_6_10_13_16_distill_mse_A/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/byol_us_mobilenetv2_cifar100_sandwichOnce3T_mse_distill_A/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/byol_us_mobilenetv2_cifar100_sandwichOnce3T_mse_distill_feat_17_distill_amse_A/checkpoint.pth.tar
    #PRETRAINED: /data/train_log_OFA/cifar100/mbv2/byol_us_mobilenetv2_cifar100_sandwichOnce3T_mse_distill_groupreg_linear_lambda_2.5e-4_alpha_0.05_dynamic_200_bins_8_warmup_100_A/checkpoint.pth.tar
    PRETRAINED: /data/train_log_OFA/cifar100/mbv2/simclr_momentum_max_with_momentum_mbv2_cifar100_sandwich3T_asymmertric_mse_distill_groupreg_A_800ep/checkpoint.pth.tar
    NUM_CLASSES: 100
    OFA:
        CALIBRATE_BN: True
        NUM_SAMPLE_TRAINING: 1
        WIDTH_MULT: 0.3
        SANDWICH: False
TRAIN:
    EPOCHS: 100
    USE_DDP: True
    LINEAR_EVAL: True
    DATASET: cifar100
    BATCH_SIZE: 128 # per-gpu
    OPTIMIZER: 
        NAME: sgd
        MOMENTUM: 0.9
        WEIGHT_DECAY: 0.000 # 1e-5
    LR_SCHEDULER:
        WARMUP_EPOCHS: 0
        WARMUP_LR: 0.0002 # 1e-4
        BASE_LR: 30.0 # 1e-2
        #BASE_LR: 0.1 
        MIN_LR: 0.
        #TYPE: cosine
        TYPE: multiStep
        DECAY_RATE: 0.1
        DECAY_MILESTONES : [60, 80]
    LOSS: 
        CRITERION:
            NAME: CrossEntropy
        #REGULARIZER:
        #    NAME: PACT
        LAMBDA: 0.0001
    METER:
        NAME: ACC
        ACC:
            TOPK: [1, 5]
    RUNNER:
        NAME: default
AUG:
    TRAIN:
        HORIZONTAL_FLIP:
            PROB: 0.5
        RANDOMRESIZEDCROP:
            ENABLE: True
            SCALE: (0.08, 1.0)
            INTERPOLATION: bilinear
        #RANDOMCROP:
        #    ENABLE: True
        #    PADDING: 4
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
    EVALUATION:
        RESIZE: 
            ENABLE: True
            SIZE: [224, 224]
        #RESIZE: 
        #    ENABLE: False
        #    SIZE: [32, 32]
        CENTERCROP: 
            ENABLE: False
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]