SEED: 100
MODEL:
    #ARCH: us_cifar_resnet18
    #ARCH: us_cifar_resnet18_v2
    #ARCH: cifar_resnet18
    #ARCH: us_resnet18
    #ARCH: us_resnet50
    ARCH: us_cifar_resnet18
    #ARCH: us_cifar_mobilenetv2
    INPUTSHAPE: [32, 32]
    PRETRAINED: ./train_log_OFA/cifar100/r18/ours_base_mse_distill_mse_400ep/checkpoint.pth.tar
    NUM_CLASSES: 100
    OFA:
        CALIBRATE_BN: True
        NUM_SAMPLE_TRAINING: 1
        WIDTH_MULT: 0.5
        SANDWICH: False
TRAIN:
    EPOCHS: 100
    USE_DDP: True
    LINEAR_EVAL: True
    DATASET: cifar100
    BATCH_SIZE: 128 # per-gpu
    OPTIMIZER:
        NAME: sgd
        MOMENTUM: 0.9
        WEIGHT_DECAY: 0.000 # 1e-5
    LR_SCHEDULER:
        WARMUP_EPOCHS: 0
        WARMUP_LR: 0.0002 # 1e-4
        BASE_LR: 30.0 # 1e-2
        #BASE_LR: 0.1
        MIN_LR: 0.
        #TYPE: cosine
        TYPE: multiStep
        DECAY_RATE: 0.1
        DECAY_MILESTONES : [60, 80]
    LOSS:
        CRITERION:
            NAME: CrossEntropy
        #REGULARIZER:
        #    NAME: PACT
        LAMBDA: 0.0001
    METER:
        NAME: ACC
        ACC:
            TOPK: [1, 5]
    RUNNER:
        NAME: default
AUG:
    TRAIN:
        HORIZONTAL_FLIP:
            PROB: 0.5
        RANDOMRESIZEDCROP:
            ENABLE: True
            SCALE: (0.08, 1.0)
            INTERPOLATION: bilinear
        #RANDOMCROP:
        #    ENABLE: True
        #    PADDING: 4
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
    EVALUATION:
        RESIZE:
            ENABLE: True
            SIZE: [224, 224]
        #RESIZE:
        #    ENABLE: False
        #    SIZE: [32, 32]
        CENTERCROP:
            ENABLE: False
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]