SEED: 100
MODEL:
    ARCH: s_cifar_resnet18
    #ARCH: usprune_cifar_resnet18
    INPUTSHAPE: [32, 32]
    #CHECKPOINT: /data/train_log_OFA/ciar100/r18/byol_s_r18_cifar100/checkpoint.pth.tar
    OFA:
        DISTILL: True
        DISTILL_STUDENT_TEMP: 0.1
        DISTILL_TEACHER_TEMP: 0.04
        DISTILL_FEATURE: True
        DISTILL_FEATURE_NAME: ["layer3.1.bn2","layer4.1.bn2"]
        DISTILL_FEATURE_DIM: [256, 512]
        USE_SLIMMABLE: True
        WIDTH_MULT_LIST: [1.0, 0.75, 0.5, 0.25]
        #WIDTH_MULT_LIST: [1.0, 0.5]
        #WIDTH_MULT_LIST: [0.25]
TRAIN:
    EPOCHS: 400
    USE_DDP: True
    DROP_LAST: False # set it to true for DINO
    SYNC_BN: False
    DATASET: cifar100
    BATCH_SIZE: 128 # per-gpu
    PRINT_FREQ: 10
    OPTIMIZER: 
        NAME: sgd
        MOMENTUM: 0.9
        WEIGHT_DECAY: 0.0005 # 1e-5
    LR_SCHEDULER:
        WARMUP_EPOCHS: 0
        WARMUP_LR: 0.0002 # 1e-4
        BASE_LR: 0.05 # 1e-2
        MIN_LR: 0.
        TYPE: cosine
    LOSS: 
        CRITERION:
            NAME: CosineSimilarity
        #REGULARIZER:
        #    NAME: PACT
        LAMBDA: 0.0001
    METER:
        NAME: average
        ACC:
            TOPK: [1, 5]
    RUNNER:
        NAME: ssl
AUG:
    TRAIN:
        HORIZONTAL_FLIP:
            PROB: 0.5
        RANDOMRESIZEDCROP:
            ENABLE: True
            SCALE: (0.08, 1.0)
            INTERPOLATION: bilinear
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
    EVALUATION:
        RESIZE: 
            ENABLE: True
            SIZE: [32, 32]
        CENTERCROP: 
            ENABLE: True
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
SSL:
    TYPE: BYOL
    SETTING:
        DIM: 2048
        HIDDEN_DIM: 2048
        MOMENTUM: 0.99
