SEED: 100
MODEL:
    ARCH: us_cifar_resnet50
    #ARCH: cifar_resnet18
    #ARCH: usprune_cifar_resnet18
    #ARCH: usprune_v2_cifar_resnet18
    INPUTSHAPE: [32, 32]
    #CHECKPOINT: /data/train_log_OFA/cifar100/r50/byol_us_r50_cifar100_sandwichOnce_mse_distill_feat_2_3_4_distill_amse_A/checkpoint.pth.tar
    #CHECKPOINT: /data/train_log_OFA/cifar100/r50/byol_us_r50_cifar100_sandwichOnce_mse_distill_feat_1_2_3_4_distill_mse_A/checkpoint.pth.tar
    #CHECKPOINT: /data/train_log_OFA/cifar100/r50/byol_us_r50_cifar100_sandwichOnce3T_mse_distill_A_800ep/checkpoint.pth.tar
    #CHECKPOINT: /data/train_log_OFA/cifar100/r50/byol_us_r50_cifar100_sandwichOnce3T_mse_distill_A/checkpoint.pth.tar
    OFA:
        WIDTH_MULT_RANGE: [0.25, 1.0] 
        NUM_SAMPLE_TRAINING: 3
        WIDTH_MULT: 1.0
        SANDWICH: True
        SAMPLE_SCHEDULER: A
        MOMENTUM_UPDATE: False # False: only update momentum encoder once (max model forward pass)
        DISTILL: True
        DISTILL_CRITERION: CosineSimilarity # distill final representation
        DISTILL_STUDENT_TEMP: 1.0
        DISTILL_TEACHER_TEMP: 1.0
        DISTILL_FEATURE: True
        #DISTILL_FEATURE_NAME: ["layer4.1.bn2"]
        DISTILL_FEATURE_NAME: ["layer2.3.bn2","layer3.5.bn2", "layer4.2.bn2"]
        #DISTILL_FEATURE_NAME: ["layer1.2.bn3","layer2.3.bn3","layer3.5.bn3", "layer4.2.bn3"]
        DISTILL_FEATURE_CRITERION: MSELoss # distill intermediate features
        DISTILL_FEATURE_LAMBDA: 1.0
        #DISTILL_FEATURE_DIM: [512]
        DISTILL_FEATURE_DIM: [128, 256, 512]
        #DISTILL_FEATURE_DIM: [256, 512, 1024, 2048]
        USE_SLIMMABLE: False
        WIDTH_MULT_LIST: [1.0, 0.75, 0.5, 0.25]
        REGULARIZER: True
        REGULARIZER_CRITERION: GroupReg
        REGULARIZER_LAMBDA: 0.00025
        REGULARIZER_DECAY_ALPHA: 0.05
        REGULARIZER_DECAY_TYPE: linear
        REGULARIZER_DECAY_BINS: 8
        REGULARIZER_WARMUP_EPOCHS: 200
PRUNE:
    ENABLE_PRUNE: False
    TYPE: structed
    GRANULARITY: channelwise
    STRATEGY: l1norm
    GLOBAL_FACTOR: 1.0
TRAIN:
    EPOCHS: 800
    USE_DDP: True
    SYNC_BN: False
    DROP_LAST: True # set it to true for DINO
    DATASET: cifar100
    BATCH_SIZE: 64 # per-gpu 
    PRINT_FREQ: 10
    OPTIMIZER: 
        NAME: sgd
        MOMENTUM: 0.9
        WEIGHT_DECAY: 0.0005 # 1e-5
    LR_SCHEDULER:
        WARMUP_EPOCHS: 0
        WARMUP_LR: 0.0002 # 1e-4
        BASE_LR: 0.05 # 1e-2
        MIN_LR: 0.
        TYPE: cosine
    LOSS: 
        CRITERION:
            NAME: CosineSimilarity
        #REGULARIZER:
        #    NAME: PACT
        LAMBDA: 0.0001
    METER:
        NAME: average
        ACC:
            TOPK: [1, 5]
    RUNNER:
        NAME: ssl
AUG:
    TRAIN:
        HORIZONTAL_FLIP:
            PROB: 0.5
        RANDOMRESIZEDCROP:
            ENABLE: True
            SCALE: (0.08, 1.0)
            INTERPOLATION: bilinear
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
    EVALUATION:
        RESIZE: 
            ENABLE: True
            SIZE: [32, 32]
        CENTERCROP: 
            ENABLE: True
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
SSL:
    TYPE: BYOL
    SETTING:
        DIM: 2048
        HIDDEN_DIM: 2048
        MOMENTUM: 0.99

