SEED: 100
MODEL:
    ARCH: us_cifar_resnet18
    INPUTSHAPE: [32, 32]
    OFA:
        WIDTH_MULT_RANGE: [0.25, 1.0] 
        NUM_SAMPLE_TRAINING: 3
        WIDTH_MULT: 0.5
        MOMENTUM_UPDATE: False
        SANDWICH: True
        SAMPLE_SCHEDULER: ""
        DISTILL: True
        DISTILL_CRITERION: CosineSimilarity
        DISTILL_STUDENT_TEMP: 0.5
        DISTILL_TEACHER_TEMP: 0.01
        USE_SLIMMABLE: False
        WIDTH_MULT_LIST: [1.0, 0.75, 0.5, 0.25]
        REGULARIZER: False
        REGULARIZER_CRITERION: GroupReg
        REGULARIZER_LAMBDA: 0.00005
        REGULARIZER_L1_LAMBDA: 0.00005
        REGULARIZER_DECAY_ALPHA: 0.05
        REGULARIZER_DECAY_TYPE: linear
        REGULARIZER_DECAY_BINS: 8
        REGULARIZER_WARMUP_EPOCHS: 100
TRAIN:
    EPOCHS: 400
    USE_DDP: True
    SYNC_BN: False
    DATASET: cifar100
    BATCH_SIZE: 128 # per-gpu
    OPTIMIZER: 
        NAME: sgd
        MOMENTUM: 0.9
        WEIGHT_DECAY: 0.0001 # 1e-5
    LR_SCHEDULER:
        WARMUP_EPOCHS: 0
        WARMUP_LR: 0.0002 # 1e-4
        BASE_LR: 0.5 # 1e-2
        MIN_LR: 0.
        TYPE: cosine
    LOSS: 
        CRITERION:
            NAME: InfoNCEv2
        #REGULARIZER:
        #    NAME: PACT
        LAMBDA: 0.0001
    METER:
        NAME: average
        ACC:
            TOPK: [1, 5]
    RUNNER:
        NAME: ssl
AUG:
    TRAIN:
        HORIZONTAL_FLIP:
            PROB: 0.5
        RANDOMRESIZEDCROP:
            ENABLE: True
            SCALE: (0.08, 1.0)
            INTERPOLATION: bilinear
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
    EVALUATION:
        RESIZE: 
            ENABLE: True
            SIZE: [32, 32]
        CENTERCROP: 
            ENABLE: True
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
SSL:
    TYPE: SimCLR
    SETTING:
        DIM: 256
        HIDDEN_DIM: 2048
        T: 0.5
        MLP: TRUE
        MOMENTUM: 0.99