SEED: 100
MODEL:
    ARCH: us_cifar_resnet18
    #ARCH: cifar_resnet18
    #ARCH: usprune_cifar_resnet18
    #ARCH: usprune_v2_cifar_resnet18
    INPUTSHAPE: [32, 32]
    OFA:
        WIDTH_MULT_RANGE: [0.25, 1.0] 
        NUM_SAMPLE_TRAINING: 4
        WIDTH_MULT: 0.25
        SANDWICH: True
        SAMPLE_SCHEDULER: ""
        MOMENTUM_UPDATE: True # False: only update momentum encoder once (max model forward pass)
        DISTILL: True
        DISTILL_CRITERION: CosineSimilarity
        DISTILL_FEATURE: False
        DISTILL_STUDENT_TEMP: 0.1
        DISTILL_TEACHER_TEMP: 0.04
        USE_SLIMMABLE: False
        WIDTH_MULT_LIST: [1.0, 0.75, 0.5, 0.25]
        REGULARIZER: False
        REGULARIZER_CRITERION: GroupReg
        REGULARIZER_LAMBDA: 0.00025
        REGULARIZER_L1_LAMBDA: 0.00005
        REGULARIZER_DECAY_ALPHA: 0.05
        REGULARIZER_DECAY_TYPE: linear
        REGULARIZER_DECAY_BINS: 8
        REGULARIZER_WARMUP_EPOCHS: 100
PRUNE:
    ENABLE_PRUNE: False
    TYPE: structed
    GRANULARITY: channelwise
    STRATEGY: l1norm
    GLOBAL_FACTOR: 1.0
TRAIN:
    EPOCHS: 400
    USE_DDP: True
    SYNC_BN: False
    DROP_LAST: True # set it to true for DINO
    DATASET: cifar100
    BATCH_SIZE: 128 # per-gpu
    PRINT_FREQ: 10
    OPTIMIZER: 
        NAME: sgd
        MOMENTUM: 0.9
        WEIGHT_DECAY: 0.0005 # 1e-5
    LR_SCHEDULER:
        WARMUP_EPOCHS: 0
        WARMUP_LR: 0.0002 # 1e-4
        BASE_LR: 0.05 # 1e-2
        MIN_LR: 0.
        TYPE: cosine
    LOSS: 
        CRITERION:
            NAME: CosineSimilarity
        #REGULARIZER:
        #    NAME: PACT
        LAMBDA: 0.0001
    METER:
        NAME: average
        ACC:
            TOPK: [1, 5]
    RUNNER:
        NAME: ssl
AUG:
    TRAIN:
        HORIZONTAL_FLIP:
            PROB: 0.5
        RANDOMRESIZEDCROP:
            ENABLE: True
            SCALE: (0.08, 1.0)
            INTERPOLATION: bilinear
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
    EVALUATION:
        RESIZE: 
            ENABLE: True
            SIZE: [32, 32]
        CENTERCROP: 
            ENABLE: True
        NORMLIZATION:
            MEAN: [0.4914, 0.4822, 0.4465]
            STD: [0.2023, 0.1994, 0.2010]
SSL:
    TYPE: BYOL
    SETTING:
        DIM: 2048
        HIDDEN_DIM: 2048
        MOMENTUM: 0.99

